Milestone 3
javitocor/calculator-React pull request #3
Opened 2020-08-13 06:35 UTC by javitocor

Dear TSE,

In this milestone I accomplished the following requirements:
- Add style to display component
- Add style to button component
- Add props to button component
- Add propTypes to button component
- Add style to button panel component

Best regards

2020-08-14 06:28 UTC, whiz25 requested changes
## Changes Required :pray: 
You have done an amazing job in this milestone. Most requirements have been met. You need to fix a few things before we can merge.
Check my comments for suggestions.


### Martin Afani

2020-08-14 06:28 UTC, whiz25 commented on src/index.css
> +  font-size: 2.4rem;
- Text must be centered. Add the styling.

2020-08-14 06:28 UTC, whiz25 commented on src/index.css
> +.display {
- Display, App and ButtonPanel components must have a display mode of flex. Add styling for ButtonPanel.js component.

2020-08-14 06:52 UTC, javitocor commented
Added changes requested by TSE

2020-08-15 08:06 UTC, fatymahmed approved these changes
## Hi @javitocor  
### Good job making the requested changes 🎉🎉
## Status: Approved ✔️

2020-08-15 13:07 UTC, merged